version: "3"
services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=Ecem
      - WATCHPACK_POLLING=true
